<?php

namespace Database\Seeders;

use App\Models\EngineerSchedule;
use App\Models\Shift;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EngineerScheduleSeeder extends Seeder
{
    public function run(): void
    {
        $engineers = User::query()->where('role', 'engineer')->orderBy('name')->get(['id', 'email']);
        if ($engineers->isEmpty()) {
            return;
        }

        $shifts = Shift::query()->pluck('id', 'code');
        $assignedById = User::query()->where('email', 'superadmin@demo.com')->value('id');
        $startDate = Carbon::today();
        $daysToGenerate = 21;
        $rotation = ['SHIFT-DAY', 'SHIFT-EVE', 'SHIFT-NIGHT'];

        foreach ($engineers as $engineerIndex => $engineer) {
            for ($offset = 0; $offset < $daysToGenerate; $offset++) {
                $date = $startDate->copy()->addDays($offset);
                $dayOfWeek = $date->dayOfWeekIso;
                $baseShiftCode = $rotation[($engineerIndex + $offset) % count($rotation)];
                $status = EngineerSchedule::STATUS_ASSIGNED;
                $notes = 'Rotational schedule generated by master seeder.';

                if ($dayOfWeek === 7) {
                    $status = EngineerSchedule::STATUS_OFF;
                    $notes = 'Scheduled weekly off day.';
                }

                if ($engineer->email === 'gilang.prasetyo@demo.com' && $offset === 3) {
                    $status = EngineerSchedule::STATUS_LEAVE;
                    $notes = 'Approved annual leave.';
                }

                if ($engineer->email === 'irfan.setiawan@demo.com' && $offset === 5) {
                    $status = EngineerSchedule::STATUS_SICK;
                    $notes = 'Medical rest day.';
                }

                if ($engineer->email === 'engineer2@demo.com' && in_array($dayOfWeek, [6], true)) {
                    $status = EngineerSchedule::STATUS_OFF;
                    $notes = 'Weekend field support off day.';
                }

                EngineerSchedule::query()->updateOrCreate(
                    [
                        'user_id' => $engineer->id,
                        'work_date' => $date->toDateString(),
                    ],
                    [
                        'shift_id' => $shifts[$baseShiftCode] ?? $shifts['SHIFT-DAY'] ?? null,
                        'status' => $status,
                        'notes' => $notes,
                        'assigned_by_id' => $assignedById,
                    ]
                );
            }
        }
    }
}
